vich_uploader:
    db_driver: orm

    mappings:
        cmrs:
            uri_prefix: /images/cmrs
            upload_destination: '%kernel.project_dir%/public/images/cmrs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
